### ISSUE TITLE
homey_memory_used doesn't add up to homey_memory_total - homey_memory_free

### ISSUE THREAD

**Issue by klippo** [rickardp/homey-prometheus-exporter#1]
While creating a grafana dashboard I noticed that homey_memory_used doesn't add up to homey_memory_total - homey_memory_free

# curl http://homey:9414/metrics -s |grep ^homey_memory|grep -E 'total|free' | awk '{print $NF}'  | tr "\n" "-" | sed -e 's/-$//g' | bc -i|tail -n1 # TOTAL-FREE
447053824

# curl http://homey:9414/metrics -s |grep ^homey_memory|grep used| awk '{ print $NF}' | tr "\n" "+" | sed -e 's/+$//g' | bc -i|tail -n1 # USED
386704384

Approx values while testing
homey_memory_total 511995904
homey_memory_free 59482112
homey_memory_swap 524288
homey_memory_used{component="homey:app:com.fibaro"} 13509632
homey_memory_used{component="homey:app:nl.timkouters.domitech"} 12764160
homey_memory_used{component="homey:app:com.google.chromecast"} 16764928
homey_memory_used{component="homey:app:com.panasonic.viera"} 14077952
homey_memory_used{component="homey:app:com.osram.lightify.zigbee"} 12962816
homey_memory_used{component="homey:app:com.ubnt.unifi"} 25013248
homey_memory_used{component="homey:app:nl.klikaanklikuit"} 12514304
homey_memory_used{component="homey:app:com.weather-sensors"} 13585408
homey_memory_used{component="homey:app:com.telldus"} 13387776
homey_memory_used{component="homey:app:com.everspring"} 13725696
homey_memory_used{component="homey:app:nl.tonversteeg.pushbullet"} 14837760
homey_memory_used{component="homey:app:net.i-dev.betterlogic"} 13369344
homey_memory_used{component="homey:app:openmindnl.ledcollection"} 22273024
homey_memory_used{component="homey"} 109253632
homey_memory_used{component="system"} 56203264
homey_memory_used{component="homey:app:io.prometheus"} 25985024

Am I doing something wrong, or is some stats missing?

Edit: Looked at systemInfo output, and the inconsistency is there. Nothing to do with the exporter

**Comment by rickardp** [comment]
On Linux systems, neither free nor user memory include memory user for cache. It is not documented what Homey reports, but I can only guess this is part of it.
