### ISSUE TITLE
Some zero-values not exported

### ISSUE THREAD

**Issue by snorrelo** [rickardp/homey-prometheus-exporter#10]
Hi,

I'm testing the exporter and it seems some for some metrics 0-value is not exported. Looks like it is stuck on the last non-zero value. Not sure if it's related to #9 or not.

Example from `<ip>/metrics`
```
# TYPE homey_device_onoff gauge
homey_device_onoff{device="be...",name="Desk lamp",zone="Living Room",zones="Home/Living Room"} 1

# TYPE homey_device_measure_power gauge
homey_device_measure_power{device="17...",name="Heater",zone="Living Room",zones="Home/Living Room"} 1283.5
```

The first is a Philips Hue lamp, the second a Fibaro Wall Plug.

The information is correct, 0/off for both, in the Homey App. For the wall plug, it is also correct in https://insights.athom.com/. The lamp is not in insights.

My setup:
Homey (Early 2019)
Homey 2.0.0, 1/3 free memory, lots of free storage
Fibaro App 2.1.19
Hue App 3.0.10
Prometheus.io 0.2.3

**Comment by rickardp** [comment]
The fix is now published to the beta channel.
