### ISSUE TITLE
Exporting variables from homes "logic" feature. 

### ISSUE THREAD

**Issue by OttoWerse** [rickardp/homey-prometheus-exporter#14]
I think it would be a great addition to also export the user-created logical variables, since they are useful to use as counters for things like flow runs, or even just to expose additional app information (like smart presence device connections, etc.) that wouldn't otherwise be collectable.

Just numerical and boolean values would already be great, but I think string values could also be pretty useful. Especially if it would be possible to also export some of the system/app default variables, like Spotify song information or hue light modes.

Maybe this should be something configurable to the user though, since (at least to me) it sounds like it could strain homeys CPU quite a bit.

**Comment by rickardp** [comment]
Exporting numerical (and Boolean) variables looks quite doable and should be quite lean on the system as there is an event-based API for it. Exporting any kind of strings is always going to be tricky unless the strings can be mapped to a finite set of values (like an enumeration).

As for configurability I have a design goal of not having any type of settings/configuration for the exporter itself. So far it has been possible to follow without much trouble.

So I think for the first version just exporting numerical and bools would be quite useful.

As for the others (like Hue light mode) it should already be exported as part of the device state for the Hue bulbs.

**Comment by psy0rz** [comment]
It would also be great is this worked for the Better Logic app.

**Comment by rickardp** [comment]
Doing some spring cleaning here. This was fixed in v0.2.6.
