### ISSUE TITLE
Not show all readings in grafana

### ISSUE THREAD

**Issue by robvos** [rickardp/homey-prometheus-exporter#17]
I have setup Prometheus and Grafana.
When I make a graph in Grafana of the power metrics I get the complete list. About 20 devices.

Is it possible in Grafana to select which devices I want to see?
In the Prometheus graph I can switch them of.

Sorry for my bad English. I hope you understand what I mean.

**Comment by rickardp** [comment]
You can click the series on the graph to toggle them, if that is what you meant. If you want something more permanent, you can select based on the labels : https://prometheus.io/docs/prometheus/latest/querying/basics/#instant-vector-selectors
