### ISSUE TITLE
App does not start correctly after Homey reboot

### ISSUE THREAD

**Issue by paaland** [rickardp/homey-prometheus-exporter#18]
After a Homey reboot (I experience zwave instability and have it reboot once a week) the Prometheus app does not start correctly so no data is sent to Prometheus until I restart the app on the Homey. I suspect the app starts before everything is ready on the Homey or something like that.

**Comment by Jesa-a1** [comment]
Just want to add that I have the same problem. Made a flow to get around it.
![image](https://user-images.githubusercontent.com/43587912/147817199-e0270510-bd8c-4851-9164-ec6e875589a4.png)

**Comment by rickardp** [comment]
That's a weird one, if it is not a one off. If the app itself stops, I suppose it means it crashed completely. Could you send a diagnostic trace next time this happens?

I would have expected to seen some error reports in the developer page. Another possibility is that the Homey simply doesn't start the app for some reason. I did see the app simply left in stopped state after a recent upgrade, but I was running local build so I am unsure if it was this issue or not. Is this what you saw too?

**Comment by Jesa-a1** [comment]
How to I send a diagnostic trace?

After Homey boot the app do not produce any metrics web page, until the app is restarted

  "session": "44762c82-93aa-48c2-9eaa-ceeef03802ee",
  "ready": true,
  "state": "running",
  "crashed": false,
  "crashedMessage": null,
  "exitCode": null,
  "exitSignal": null,
  "exitCount": 0,

Before booting Homey
  "usage": {
    "cpu": 0.00017762912184609246,
    "mem": 25858048

After booting Homey, before restart of app
  "usage": {
    "cpu": 3.345260901711016e-7,
    "mem": 18289664

**Comment by mikrofyr** [comment]
Related, app does not start up after update. Above Flow workaround does not work in this case.

Disable auto update to prevent data holes.

**Comment by rickardp** [comment]
It seems that sometimes the internal calls to Homey APIs time out after 30 seconds. I have not (yet) seen the issue on the latest Homey firmware though
