### ISSUE TITLE
Add device-type and/or the source app as key

### ISSUE THREAD

**Issue by josefzahner** [rickardp/homey-prometheus-exporter#20]
I’ve the issue that the “homey_device_measure_temperature” key has a lot of different temperatures, some of them (of a specific device type from one vendor) are reporting not a room but the device temperature - which is not important for end users. So I need to filter the device temperatures out. However I have no option to filter, exception for the “name”. As I know the device/type and app, is there any option to add a key/value-pair for the device-type and/or the app? Today I see the following keys:

- device
- instance
- job
- name
- zone
- zones

**Comment by rickardp** [comment]
In the latest version you have "device" which is the driver app ID, "device_id" which is the device type ID within the app, and "class" which is the Homey device class. I believe these would cover your use case.
