### ISSUE TITLE
Very high CPU load with v0.2.10

### ISSUE THREAD

**Issue by josefzahner** [rickardp/homey-prometheus-exporter#25]
As soon as I'm enabling the prometheus homey app, I see a drastically increased CPU load on my homey. Without prometheus I've between 50-100% load (with a few higher peaks), but as soon as I'm enabling prometheus app between 250-300% load! That's way too much and has impact to all my other apps...
![Screenshot 2022-09-07 at 21 16 36](https://user-images.githubusercontent.com/33521474/188960883-2da2bb88-2000-4f5f-af01-0d45c5fd95c2.png)

**Comment by rickardp** [comment]
Can you please send a diagnostics report?
Also, can you please install dashboard 10586 and see those graphs to see what is taking time. 

I've seen before both that some drivers are spamming device updates but also that the polling loop takes time.

**Comment by josefzahner** [comment]
I can't create a diagnostic report -> "Entity too large"... 
![IMG_5AED348ED03A-1](https://user-images.githubusercontent.com/33521474/188984135-5ccacf6a-5d84-458d-897c-017bf2555bde.jpeg)

Grafana Dashboard Screenshot, please guide me to the right direction, I've a lot of devices...:
![Screenshot 2022-09-07 at 23 03 36](https://user-images.githubusercontent.com/33521474/188979193-ca0dbe67-6ac5-49ac-9c45-f3c55749787a.png)

**Comment by josefzahner** [comment]
Ok, I retried to create a diagnose report:
515de8e4-130b-42d1-9bbf-d8d1fb3d0e72

**Comment by rickardp** [comment]
Thanks, I got the report. In the dashboard, there is a device with a really high call rate, can you check which device it is?
I would say in general the issue is that you get up to 25.9 device updates per second, that's a lot of metrics. Also, can you check what the top 3 ones are on "Time spent"?

**Comment by josefzahner** [comment]
Correct, the highest device from "Call rate per device" is the energy meter for my house and the solar panels. It is a device from the "SMA Energy" app. It generates the following metrics:
`~/Downloads/metrics_promi_homey.txt:854: homey_exporter_self_time_seconds{type="user",action="deviceupdate",device="a203047e-5949-4a70-9c21-eff24f763bec",name="Sunny Home Manager 2",zone="Waschküche",zones="Zuhause/Untergeschoss/Waschküche"} 0.051763999999999984
~/Downloads/metrics_promi_homey.txt:855: homey_exporter_self_time_seconds{type="system",action="deviceupdate",device="a203047e-5949-4a70-9c21-eff24f763bec",name="Sunny Home Manager 2",zone="Waschküche",zones="Zuhause/Untergeschoss/Waschküche"} 0.015068000000000005
~/Downloads/metrics_promi_homey.txt:856: homey_exporter_self_time_seconds{type="real",action="deviceupdate",device="a203047e-5949-4a70-9c21-eff24f763bec",name="Sunny Home Manager 2",zone="Waschküche",zones="Zuhause/Untergeschoss/Waschküche"} 0.044000000000000025
~/Downloads/metrics_promi_homey.txt:857: homey_exporter_self_time_seconds{type="real",action="registerdevice",device="a203047e-5949-4a70-9c21-eff24f763bec",name="Sunny Home Manager 2",zone="Waschküche",zones="Zuhause/Untergeschoss/Waschküche"} 0.030000000000000002
~/Downloads/metrics_promi_homey.txt:858: homey_exporter_self_time_seconds{type="user",action="registerdevice",device="a203047e-5949-4a70-9c21-eff24f763bec",name="Sunny Home Manager 2",zone="Waschküche",zones="Zuhause/Untergeschoss/Waschküche"} 0.02703
~/Downloads/metrics_promi_homey.txt:859: homey_exporter_self_time_seconds{type="system",action="registerdevice",device="a203047e-5949-4a70-9c21-eff24f763bec",name="Sunny Home Manager 2",zone="Waschküche",zones="Zuhause/Untergeschoss/Waschküche"} 0
~/Downloads/metrics_promi_homey.txt:1249: homey_exporter_self_call_count{action="deviceupdate",device="a203047e-5949-4a70-9c21-eff24f763bec",name="Sunny Home Manager 2",zone="Waschküche",zones="Zuhause/Untergeschoss/Waschküche"} 178
~/Downloads/metrics_promi_homey.txt:1250: homey_exporter_self_call_count{action="registerdevice",device="a203047e-5949-4a70-9c21-eff24f763bec",name="Sunny Home Manager 2",zone="Waschküche",zones="Zuhause/Untergeschoss/Waschküche"} 2
~/Downloads/metrics_promi_homey.txt:1354: homey_device_measure_power{device="a203047e-5949-4a70-9c21-eff24f763bec",name="Sunny Home Manager 2",zone="Waschküche",zones="Zuhause/Untergeschoss/Waschküche",class="sensor"} 1096
~/Downloads/metrics_promi_homey.txt:2160: homey_device_measure_power_surplus{device="a203047e-5949-4a70-9c21-eff24f763bec",name="Sunny Home Manager 2",zone="Waschküche",zones="Zuhause/Untergeschoss/Waschküche",class="sensor"} 0
~/Downloads/metrics_promi_homey.txt:2164: homey_device_measure_power_L1{device="a203047e-5949-4a70-9c21-eff24f763bec",name="Sunny Home Manager 2",zone="Waschküche",zones="Zuhause/Untergeschoss/Waschküche",class="sensor"} 565
~/Downloads/metrics_promi_homey.txt:2168: homey_device_measure_current_L1{device="a203047e-5949-4a70-9c21-eff24f763bec",name="Sunny Home Manager 2",zone="Waschküche",zones="Zuhause/Untergeschoss/Waschküche",class="sensor"} 2.87
~/Downloads/metrics_promi_homey.txt:2172: homey_device_measure_power_L2{device="a203047e-5949-4a70-9c21-eff24f763bec",name="Sunny Home Manager 2",zone="Waschküche",zones="Zuhause/Untergeschoss/Waschküche",class="sensor"} 259
~/Downloads/metrics_promi_homey.txt:2176: homey_device_measure_current_L2{device="a203047e-5949-4a70-9c21-eff24f763bec",name="Sunny Home Manager 2",zone="Waschküche",zones="Zuhause/Untergeschoss/Waschküche",class="sensor"} 1.18
~/Downloads/metrics_promi_homey.txt:2180: homey_device_measure_power_L3{device="a203047e-5949-4a70-9c21-eff24f763bec",name="Sunny Home Manager 2",zone="Waschküche",zones="Zuhause/Untergeschoss/Waschküche",class="sensor"} 273
~/Downloads/metrics_promi_homey.txt:2184: homey_device_measure_current_L3{device="a203047e-5949-4a70-9c21-eff24f763bec",name="Sunny Home Manager 2",zone="Waschküche",zones="Zuhause/Untergeschoss/Waschküche",class="sensor"} 1.17
~/Downloads/metrics_promi_homey.txt:2188: homey_device_frequency{device="a203047e-5949-4a70-9c21-eff24f763bec",name="Sunny Home Manager 2",zone="Waschküche",zones="Zuhause/Untergeschoss/Waschküche",class="sensor"} 50.01
`
"Time spent per device" -> Two of them are old Open Weather Device and one is my Withing scale. 
![Screenshot 2022-09-08 at 22 06 37](https://user-images.githubusercontent.com/33521474/189216238-31b60a54-8877-4b5b-a93d-7e79de3636ad.png)

So the question is now, how can we improve the whole thing. 200% more average load is not acceptable for my homey, everything gets slow due to the high load ;-)

**Comment by rickardp** [comment]
I just updated the app with some optimizations to the hot path of the device update callback. I don't expect miracles, but at least there is less code to run during each update.

I think the issue here is that the device gets updated more than 25 times per second. While I could implement some kind of timer back off pattern, I think there is so little code now in the callback that it wouldn't make much of an impact. As far as I know there isn't an API in Homey to limit the update frequency on the listener side, every device update gets passed.

Is there a real need to have this device update this fast? Otherwise a solution might be to request the app developer to update the caps less frequently?

**Comment by josefzahner** [comment]
With "just updated" you mean the v0.3.1 version?

Which device do you mean by "update so fast", the energy meter? The reason for the updates in 5s interval there is, that you would like to see the energy consumption as fast as possible. Eg. if you use your toast you wanna see that on the energy meter and you don't want to wait 30s...

**Comment by rickardp** [comment]
Can you please report back if the numbers look the same with the new version? Also, it would be helpful if you could expand the box called "Time spent" to see what is taking the most time.

**Comment by josefzahner** [comment]
I've deleted now some unneeded open weather devices and as well the withings scale. I activated again your app with v0.3.1. Let's see in the next few minutes whats happening on the cpu load.

**Comment by josefzahner** [comment]
> Can you please report back if the numbers look the same with the new version? Also, it would be helpful if you could expand the box called "Time spent" to see what is taking the most time.

I'll do that in a few minutes. Let's wait a bit.

**Comment by rickardp** [comment]
I've also got around 100+ devices by the way. "Worst" device I see is the Easee load balancer, which peaks at around 0.5 updates per second. After the update I could see the device update time go down by a large percentage, but it is from a very low level.

Interestingly, the system info poll seems to have increased recently, but not tied to an update. I will check it it correlates with a Homey OS update.

**Comment by josefzahner** [comment]
Ok - he we go.
![Screenshot 2022-09-08 at 23 01 58](https://user-images.githubusercontent.com/33521474/189225253-a2b78786-e20f-43ff-b1e1-697b1fb656a3.png)

![Screenshot 2022-09-08 at 23 02 31](https://user-images.githubusercontent.com/33521474/189225389-15931ef2-9c24-4ea4-be2b-ff8d566da610.png)

![Screenshot 2022-09-08 at 23 03 26](https://user-images.githubusercontent.com/33521474/189225450-bd675bde-6dc5-4a8f-a945-5619918fe84e.png)

**Comment by josefzahner** [comment]
I've as well a easee home, but it wasn't connected to my car during the test. 15m load is still at 200%.

So you say one thing is the systeminfo (time spent) and the other culprit will be the "sunny home manager 2" from "call rate per device". An option would be to delete the device for the test - but at the end it doesn't help because i really need this device... to display the energy consumption on my dashboard

**Comment by josefzahner** [comment]
I've deleted the "Sunny Home Manager 2" device. The deviceupdate call rate went down from 20 to 18.6. Load average is more or less the same. So it doesn't makes much difference.

**Comment by rickardp** [comment]
I think I misread your first picture, sorry about that. The deviceupdate was not 25/sec, that was the stacked total. Then it is more or less the same as mine. I think the main difference between your dashboard and mine is the polling loop (systeminfo). I think I will add some more fine grained metrics on what in that method takes time to try to isolate the problem to which Homey API call is the culprit.

**Comment by josefzahner** [comment]
Perfect, thanks a lot for tacking care of it. Any idea's what could cause the long plling loop (systeminfo) time? Shouldn't that be the same for more or less every homey?

**Comment by rickardp** [comment]
Version 0.3.2 improves self metrics on the polling, and also reduces the storage polling which I suspect could be the culprit. Can be installed as a test version for now https://homey.app/sv-se/app/io.prometheus/Prometheus.io/test/

> Shouldn't that be the same for more or less every homey?

It seems to not be the case. I am not sure why. My suspicion is that it is the call to the getStorageInfo that sometimes cause issues (based on the fact that I can see error reports on this call timing out). Maybe things such as a lot of installed apps, worn-out flash drive or different hardware revisions on the Homey could impact? Anyway, we should see if this is what causes problems for you after this.

**Comment by josefzahner** [comment]
Ok 0.3.2 installed. Load average went down a bit, but is still high:
![Screenshot 2022-09-10 at 20 51 32](https://user-images.githubusercontent.com/33521474/189497674-d169d6b5-b717-46ad-9cc6-acb570e8a3bd.png)

**Comment by josefzahner** [comment]
This is the homey insight graph. Base load is as well massively higher than before enabling prometheus.io. I'm using a real homey Pro (2019), bought end of 2019. About 35 apps installed, but not all enabled. Storage not even half filled.

![Screenshot 2022-09-10 at 21 02 18](https://user-images.githubusercontent.com/33521474/189498103-5e7ca5a2-27bb-4c26-b1ed-3698e1865627.png)

**Comment by rickardp** [comment]
Thanks for the info. It confirms the storage info call is crazy expensive for some people. Since it is not crucial to update this with high frequency, I am considering setting a higher update interval on this as a solution, at least temporarily until it is possible to figure out why it is so expensive.

**Comment by rickardp** [comment]
0.3.3 significantly lowers the frequency for storage updates. Can you please report how this works, and also please share the update times ("Time spent") for all labels?

**Comment by josefzahner** [comment]
v0.3.3 Graph:
![Screenshot 2022-09-10 at 21 53 53](https://user-images.githubusercontent.com/33521474/189499786-fae60e72-404f-42a8-bee3-1e065ecf8287.png)
![Screenshot 2022-09-10 at 21 54 26](https://user-images.githubusercontent.com/33521474/189499787-007d6e3c-5dae-4c1c-a1df-e2a379cd256c.png)

**Comment by rickardp** [comment]
Interesting indeed. It looks like the storage info scanning takes ~20 seconds to complete on your device, with a nontrivial amount of kernel time. The API call takes no parameters that lets me control how long this takes. When I first added this feature, it took maybe a second or two on my Homey, but that was on firmware version 2.something. I think the only reasonable thing to do is to leave this interval significantly higher (currently 10 minutes which is what I will keep).

It makes sense that, for example, they added more detailed directory scanning to calculate sizes (which would possibly explain the high kernel time %) in newer versions of the Homey, but I still don't understand why it differs between different Homeys. The only thing I can think of is if some apps are published with significantly more files which makes directory scanning more expensive, but that's just a hypothesis.

Anyway, I will now publish version 0.3.3 and consider this issue to be resolved.

**Comment by rickardp** [comment]
Version 0.3.3 is live, which resolves the high CPU usage by increasing the time interval between polling of storage stats.
