### ISSUE TITLE
Prometheus stopping / crashing after 0.00 hours (v.0.3.3)

### ISSUE THREAD

**Issue by hfvdv** [rickardp/homey-prometheus-exporter#26]
App still crashing after 0.00 hours daily. Current version v.0.3.3

**Comment by rickardp** [comment]
I received the following crash report from around midnight tonight:
```

  unknown_network_interface: An unknown error has occurred [unknown_network_interface]
    at /node_modules/athom-api/dist/index.js:1:1044195
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Is something happening with Wi-Fi connectivity on your network around this time?

**Comment by hfvdv** [comment]
Between 8 and 11 november had a restart in place every hour. Removed that again
What does appear significant is response size increase since the 8th

Network (2nd graph ) also appears fairly stable and not packetloss recent 8 days

***@***.***

***@***.***
From: Hendrick van der Veen ***@***.***>
Date: Monday, 12 September 2022 at 12:36
To: rickardp/homey-prometheus-exporter ***@***.***>, rickardp/homey-prometheus-exporter ***@***.***>
Cc: hfvdv ***@***.***>, Author ***@***.***>
Subject: Re: [rickardp/homey-prometheus-exporter] Prometheus stopping / crashing after 0.00 hours (v.0.3.3) (Issue #26)
Not that I am aware of. I will investigate and check some other logs. Do find it odd it appears to be happening always after midnight. I have plus 90 devices on my network. Both wired and wireless. Homey is wireless ofc


________________________________

**Comment by hfvdv** [comment]
Hi Rickard,

Just to let you know it crashed again today at 0.00.

From: Hendrick van der Veen ***@***.***>
Date: Monday, 12 September 2022 at 12:44
To: rickardp/homey-prometheus-exporter ***@***.***>, rickardp/homey-prometheus-exporter ***@***.***>
Cc: hfvdv ***@***.***>, Author ***@***.***>
Subject: Re: [rickardp/homey-prometheus-exporter] Prometheus stopping / crashing after 0.00 hours (v.0.3.3) (Issue #26)
Between 8 and 11 november had a restart in place every hour. Removed that again
What does appear significant is response size increase since the 8th

Network (2nd graph ) also appears fairly stable and not packetloss recent 8 days

***@***.***

***@***.***
From: Hendrick van der Veen ***@***.***>
Date: Monday, 12 September 2022 at 12:36
To: rickardp/homey-prometheus-exporter ***@***.***>, rickardp/homey-prometheus-exporter ***@***.***>
Cc: hfvdv ***@***.***>, Author ***@***.***>
Subject: Re: [rickardp/homey-prometheus-exporter] Prometheus stopping / crashing after 0.00 hours (v.0.3.3) (Issue #26)
Not that I am aware of. I will investigate and check some other logs. Do find it odd it appears to be happening always after midnight. I have plus 90 devices on my network. Both wired and wireless. Homey is wireless ofc


________________________________

**Comment by hfvdv** [comment]
Just crashed again.

Provided crash report. Perhaps it helps.

08686248-5845-4ed9-8561-6eb62a87fef3
________________________________

**Comment by rickardp** [comment]
Still the "unknown_network_interface". Unfortunately it doesn't say which API call failed. Is it possible that your wifi network is temporarily down at precisely this time? (Some APs run channel optimization every day for example). Not sure why it would impact calling local APIs, just a thought.

**Comment by hfvdv** [comment]
Not that I am aware of. I will investigate and check some other logs. Do find it odd it appears to be happening always after midnight. I have plus 90 devices on my network. Both wired and wireless. Homey is wireless ofc


________________________________

**Comment by rickardp** [comment]
Closing this as I have not seen any reports of this error recently. Please open issue if this happens again
