### ISSUE TITLE
Problem with /metrics page

### ISSUE THREAD

**Issue by w1dg3r** [rickardp/homey-prometheus-exporter#28]
Had it working but after a power failure at my home and the homey changed IP adress it no longer works, Have re-installed the app but can't get it working again. There is no page at http://<homey_ip>:9414/metrics.

nmap gives nothing:
nmap -sT -p- 192.x.x.186                                                                                            
Starting Nmap 7.93 ( https://nmap.org ) at 2022-10-04 21:58 CEST
Nmap scan report for homey-5c87___________6e27 (192.x.x.186)
Host is up (0.0086s latency).
Not shown: 65527 closed tcp ports (conn-refused)
PORT      STATE SERVICE
22/tcp    open  ssh
53/tcp    open  domain
80/tcp    open  http
443/tcp   open  https
5355/tcp  open  llmnr
41091/tcp open  unknown
42339/tcp open  unknown
51826/tcp open  unknown

Prometheus app: 0.33

Any ideas from here?

**Comment by rickardp** [comment]
Tracked in #31. Probably fixed in 0.5.0
