### ISSUE TITLE
After reboot, Service not available 

### ISSUE THREAD

**Issue by jryberg** [rickardp/homey-prometheus-exporter#31]
Hi,

Report id 8c39ec79-e597-4413-99e4-b7285d6ac9bb

It's no longer possible to connect to the service 

// Johan

**Comment by jryberg** [comment]
Update, after restart of the app after Homey Pro restarted due to power outage it took approximate 5 min and the /metrics endpoint became responsive again.

It seems it did not recover by itself after Homey restarted. I had to manually restart the app

**Comment by rickardp** [comment]
Homey Pro was not supported. Progress is tracked in #35. Please note that a new test version is nout
