### ISSUE TITLE
conn refused /metrics page

### ISSUE THREAD

**Issue by Boostedonkey** [rickardp/homey-prometheus-exporter#34]
Hi, I am currently unable to reach the metrics page using 9414.

App version 0.33
Tried restarting homey as well as restarting and reinstalling the prometheus app on homey.

When looking at app performance in homey I can see it is using memory.

nmap:
nmap -sT -p- 192.168.*.*
Starting Nmap 7.92 ( https://nmap.org ) at 2022-12-14 16:59 UTC
Nmap scan report for homey-*******c431e (192.168.*.*)
Host is up (0.024s latency).
Not shown: 65528 closed tcp ports (conn-refused)
PORT     STATE SERVICE
22/tcp   open  ssh
53/tcp   open  domain
80/tcp   open  http
443/tcp  open  https
5080/tcp open  onscreen
5081/tcp open  sdl-ets
5355/tcp open  llmnr

I have sent a diagnostics report with 7ed02f78-fef3-4de6-8a0a-4bd37edb099d

Anything I can do here?

**Comment by rickardp** [comment]
Sorry for the late reply. I was able to reproduce the issue finally. If you're still looking, please check if the latest test version has it working https://homey.app/a/io.prometheus/test/
(The issue seems to have been that you have two devices that differ in name only by a special character)

**Comment by rickardp** [comment]
Will need to rework startup for issue #36, merging these two issues
