### ISSUE TITLE
allow for prefix in /metrics when using multiple homey's

### ISSUE THREAD

**Issue by eelco2k** [rickardp/homey-prometheus-exporter#37]
When you have multiple Homey's there is no option to give the metrics a prefix name it's always homey_
regardless the physical Homey you run it on.

So Homey Pro 2023  /metrics starts with homey_*
```
# HELP homey_boot_time Time of last Homey reboot
# TYPE homey_boot_time gauge
homey_boot_time{version="10.0.0-rc.73"} 1680941168932
```

and my first Homey Pro 2016 starts with homey_*
```
# HELP homey_boot_time Time of last Homey reboot
# TYPE homey_boot_time gauge
homey_boot_time{version="8.1.3"} 1680096455541
```

**Comment by eelco2k** [comment]
never mind, i can filter out per job

**Comment by rickardp** [comment]
This has been requested before and as you have found out, labels are the correct solution. Metric names should be static.

This document explains the reasoning: https://prometheus.io/docs/instrumenting/writing_exporters/

(This comment is more for future readers)
