### ISSUE TITLE
No response

### ISSUE THREAD

**Issue by greycreations** [rickardp/homey-prometheus-exporter#4]
Hi,

I've installed the app recently on my Homey running 1.5.8 and I cannot connect to it. In the app description it is stated that for troubleshooting, browse to http://<homey_ip>:9414/metrics. I cant get a response from there through Chrome.

Any tips on what to do?

**Comment by lauer** [comment]
works fine for me on 1.5.8

**Comment by lubbertkramer** [comment]
Working at first but now also  getting the no response page. When running it in debug modus with teh CLI (your master repo) i get the unhandled promise rejection:

Device Beweging.TrapBeneden has zwave node id 44
Registering device c1ebce43-da00-4582-acd8-090edae866e4
State changed for c1ebce43-da00-4582-acd8-090edae866e4, alarm_motion
State changed for c1ebce43-da00-4582-acd8-090edae866e4, measure_luminance
State changed for c1ebce43-da00-4582-acd8-090edae866e4, alarm_battery
State changed for c1ebce43-da00-4582-acd8-090edae866e4, measure_battery
Device Beweging.Trapboven has zwave node id 46
Registering device b31bafb7-34a9-4243-9559-aeb7d7f3dca9
State changed for b31bafb7-34a9-4243-9559-aeb7d7f3dca9, onoff
Registering device 1ce7e38b-5bff-4e32-9bd2-8ce03055238b
State changed for 1ce7e38b-5bff-4e32-9bd2-8ce03055238b, onoff
State changed for 1ce7e38b-5bff-4e32-9bd2-8ce03055238b, dim
Registering device b4b40d7b-8d1e-4f06-972e-7d5209e6331c
State changed for b4b40d7b-8d1e-4f06-972e-7d5209e6331c, onoff
State changed for b4b40d7b-8d1e-4f06-972e-7d5209e6331c, dim
Registering device 2f87f813-1ef4-4c9d-af99-24870c7775b5
State changed for 2f87f813-1ef4-4c9d-af99-24870c7775b5, onoff
State changed for 2f87f813-1ef4-4c9d-af99-24870c7775b5, dim
Registering device 418c377e-f26c-4b49-a022-90dcc8566771
State changed for 418c377e-f26c-4b49-a022-90dcc8566771, onoff
State changed for 418c377e-f26c-4b49-a022-90dcc8566771, dim
Registering device 881cce7d-0a6d-46c5-b868-7cb58ab36b4a
State changed for 881cce7d-0a6d-46c5-b868-7cb58ab36b4a, measure_water
State changed for 881cce7d-0a6d-46c5-b868-7cb58ab36b4a, meter_water
Registering device 547b5aab-4e32-48c3-8a09-b5fb84d776f8
State changed for 547b5aab-4e32-48c3-8a09-b5fb84d776f8, measure_power
State changed for 547b5aab-4e32-48c3-8a09-b5fb84d776f8, meter_offPeak
State changed for 547b5aab-4e32-48c3-8a09-b5fb84d776f8, measure_gas
State changed for 547b5aab-4e32-48c3-8a09-b5fb84d776f8, meter_gas
State changed for 547b5aab-4e32-48c3-8a09-b5fb84d776f8, meter_power
State changed for 547b5aab-4e32-48c3-8a09-b5fb84d776f8, meter_power.peak
(node:27827) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Invalid metric name
(node:27827) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by greycreations** [comment]
If it is not too much to ask for, I would really appreciate a detailed tutorial of how to setup it up from scratch, preferably coupled with a video on youtube.
I really want this app to work so that I can visualize data from my Homey in Grafana. Thank you in advance.

**Comment by rickardp** [comment]
It appears that some devices have states with invalid characters in the name. While fixing this will be trivial, I wonder if there is a complete list somewhere? The “meter_power.peak” is not mentioned anywhere in the docs AFAICS.

**Comment by lubbertkramer** [comment]
Great to hear! Let me know when you have it on Git, will try it with a CLI install then

**Comment by synegic** [comment]
Created a quick-and-dirt fix for the above error. At least, that fixed it for me.
https://github.com/rickardp/homey-prometheus-exporter/pull/5

**Comment by lubbertkramer** [comment]
Its working again :D great job!

**Comment by reulnl** [comment]
I'm trying to install this fix via homey-cli but the latest code won't validate, so I can't install this version.

Any ideas?

`✓ Validating app...
✘ Homey App did not validate against level `debug`:
schema is invalid: data.definitions['zwaveDevice'].properties['associationGroupsOptions'].properties['type'] should be object,boolean
Not installing, please fix the validation issues first`

**Comment by reulnl** [comment]
Nevermind, turned out that I needed to update homey-cli :-)

**Comment by rickardp** [comment]
Fixed in 0.1.4
