### ISSUE TITLE
Stop sending data

### ISSUE THREAD

**Issue by poblom** [rickardp/homey-prometheus-exporter#6]
With varying intervals the app stop sending some data. In my case "Load Average 1,5 and 15" displayed in the same panel in Grafana. Restarting the app will resolve the issue and reporting is restored - for some time.

Running Prometheus 2.4.2 on an rpi 3. Homey is running firmware 1.5.13-rc.11

/PO

**Comment by rickardp** [comment]
Can you browse to the metrics on port 9414? What does Prometheus report?

**Comment by poblom** [comment]
While there is no updates of Load Average in Grafana (displaying only straight lines) going to ...:9414/metrics the values is "locked" at the same level. Homey -> Settings -> System is updating the values as expected. So, it seems to be the app that somehow get a "hicup". And as I said, restarting the app restores the flow of data.

**Comment by poblom** [comment]
I notice now that also reporting memory usage get "stuck" in the same way! Restarting the app resolves.

**Comment by poblom** [comment]
In my current dashboard I only have device data from a Netatmo station and from an APC700 battery backup. Have not seen an problems there. I can add some more devices just to test it out. Would you recommend any changes in settings, scrap interval for instance?

**Comment by poblom** [comment]
Added a number of on/off devices to the dashboard and there status is reported as expected. So seems to be only polling metrics that get stuck from time to time.

**Comment by lauer** [comment]
I see the same problem, and it goes for the whole file - no values get updated after some days.

**Comment by poblom** [comment]
@rickardp  No idea what's causing this issue? As of now the app is useless (to me at least). Serving data for at best 30 min, then a restart is needed.

**Comment by rickardp** [comment]
Sorry about the late response. I did receive some error reports that the app was killed due to Homey running out of memory (or the app used too much). Maybe this was the case?

How many apps did you have, and how many devices? It would also help if I could see a log file.

I am currently updating the app for Homey 2.0 and I had to change some things to make it work. It may be worth checking if the problems are still there.

**Comment by rickardp** [comment]
The update loop is quite fragile, and there are places where an exception will just stop it. I am rewriting it to make it more robust. Hopefully that will solve the issue.

**Comment by rickardp** [comment]
Just be aware that these changes are not yet pushed.

**Comment by rickardp** [comment]
The latest released version has a number of fixes to improve stability on polling.
