### ISSUE TITLE
status homey_device_alarm_contact not changing

### ISSUE THREAD

**Issue by GreyEarl** [rickardp/homey-prometheus-exporter#9]
So, I have to open a ticket to respond on a remark I made in another ticket:

homey_device_alarm_contact keeps hanging on value 1 and is not changing. I use Zigbee windows/door sensors and now they are not registering status 0 (closed). It worked before v2.0.

The strange thing is, the devices in Homey do show normal behavior, open or closed. Only in /metrics they seem to be stuck.

@rickardp you thought this was by design, but afterwards you saw there was apparently an issue with Fibaro (Zwave) devices.

 So is this issue caused by the Prometheus app?

**Comment by rickardp** [comment]
The fix is now published to the beta channel.
